### PR TITLE
Update of my CB to FluxBB converter

### PR DESCRIPTION
**Pull request by MissGeek**
Hello,

Now that I finally got sorted out in reorganizing my local repos and generating a new public key and that I just discovered the Pull requests feature, I send you this request, so my converter in your repos can finally be updated, as I noticed that you still didn't take the archive I posted a few months ago.  Because I'm still waiting after this update so I can inform the users that are interested in migrating to FluxBB.

Thanks in advance.

### CODE REVIEW

**Comment by daris** [comment]
Can you convert these changes to unix line endings?

**Comment by MissGeek** [comment]
But how can I do it ?  I'm already on Linux and I edit my files with gedit !

**Comment by daris** [comment]
Maybe your git is not properly configured? http://help.github.com/line-endings/

http://ubuntuforums.org/showpost.php?p=5447852&postcount=6

**Comment by MissGeek** [comment]
Mmm, have I done anything wrong ?  Because I have these following warnings when I add files : warning: LF will be replaced by CRLF in myfilename.php

…while it was supposed to be like this : warning: CRLF will be replaced by LF in myfilename.php

Because I didn't know if I only needed to type '$ git config --global core.autocrlf input' or if I also needed to type ' git config --global core.autocrlf true'
So I typed both…

**Comment by daris** [comment]
When you run the `git config --global core.autocrlf input`
and next `git config --global core.autocrlf true`
the second command will overwrite the first setting

I think you should convert line endings in your files (using for example tip from [this post](http://ubuntuforums.org/showpost.php?p=5447852&postcount=6)) and set the `git config --global core.autocrlf input` which should commit the line endings as they are (without modyfing)

BTW I'm using on Windows `autocrlf = true` and editor that supports unix line endings and it seems that the line endings problem doesn't affect me :)

You can't see any difference in the gedit but you can run the `git diff` command to see what was changed

**Comment by MissGeek** [comment]
Thanks for the explanation and for the find/replace tip that I'll use until I get an answer on ubuntu-fr.org regarding the linebreak default format in Gedit.

Commit and push done !

**Comment by daris** [comment]
Thanks :)

**Comment by MissGeek** [comment]
I got the answer from a member of Ubuntu-fr.org, and it turned out that I just forgot to look at the "Save As" window… When you save a file in Geditg you have a drop-down menu next to the encoding one, where you can choose the linefeed format.  So, in the future, I'll make sure UNIX format is selected in this drop-down menu.

**Pull request merged**
